config/routes.rb
Rails.application.routes.draw do
  
  resources :arrows
  resources :score_types

  resources :scores do 
    member do
      get 'puntuar'
      post 'puntuar'
      post 'add_arrows'
      get 'finish'
    end
  end

  mount Tolk::Engine => '/tolk', :as => 'tolk'
  devise_for :users

  root 'scores#index'

   resources :android do
     collection do
       get 'acceso'
       post 'acceso'
       get 'getsesiones'
       post 'getsesiones'
    end
  end

end

app/controllers/score_types_controller.rb
class ScoreTypesController < ApplicationController
  before_action :check_permissions
  before_action :set_score_type, only: [:show, :edit, :update, :destroy]

  # GET /score_types
  # GET /score_types.json
  def index
    @score_types = ScoreType.all
  end

  # GET /score_types/1
  # GET /score_types/1.json
  def show
  end

  # GET /score_types/new
  def new
    @score_type = ScoreType.new
  end

  # GET /score_types/1/edit
  def edit
  end

  # POST /score_types
  # POST /score_types.json
  def create
    @score_type = ScoreType.new(score_type_params)

    respond_to do |format|
      if @score_type.save
        format.html { redirect_to @score_type, notice: 'Score type was successfully created.' }
        format.json { render :show, status: :created, location: @score_type }
      else
        format.html { render :new }
        format.json { render json: @score_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /score_types/1
  # PATCH/PUT /score_types/1.json
  def update
    respond_to do |format|
      if @score_type.update(score_type_params)
        format.html { redirect_to @score_type, notice: 'Score type was successfully updated.' }
        format.json { render :show, status: :ok, location: @score_type }
      else
        format.html { render :edit }
        format.json { render json: @score_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /score_types/1
  # DELETE /score_types/1.json
  def destroy
    @score_type.destroy
    respond_to do |format|
      format.html { redirect_to score_types_url, notice: 'Score type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score_type
      @score_type = ScoreType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_type_params
      params.require(:score_type).permit( 
        :name, 
        :arrows, 
        :distance_1, 
        :distance_2, 
        :distance_3, 
        :distance_4, 
        :color,
        :round,
        :letter,
        :num_rounds,
        :published)
    end

    def check_permissions 
      redirect_to root_path, notice: t('main.no_permissions') unless current_user.has_role? :admin
    end
end

app/helpers/score_types_helper.rb
module ScoreTypesHelper
end

app/views/score_types/_form.html.erb
<%= form_for(@score_type) do |f| %>
  <% if @score_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score_type.errors.count, "error") %> prohibited this score_type from being saved:</h2>

      <ul>
      <% @score_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :round %><br>
    <%= f.number_field :round %>
  </div>
  <div class="field">
    <%= f.label :letter %><br>
    <%= f.text_field :letter %>
  </div>
  <div class="field">
    <%= f.label :arrows %><br>
    <%= f.number_field :arrows %>
  </div>
  <div class="field">
    <%= f.label :distance_1 %><br>
    <%= f.number_field :distance_1 %>
  </div>
  <div class="field">
    <%= f.label :distance_2 %><br>
    <%= f.number_field :distance_2 %>
  </div>
  <div class="field">
    <%= f.label :distance_3 %><br>
    <%= f.number_field :distance_3 %>
  </div>
  <div class="field">
    <%= f.label :distance_4 %><br>
    <%= f.number_field :distance_4 %>
  </div>
  <div class="field">
    <%= f.label :num_rounds %><br>
    <%= f.number_field :num_rounds %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/score_types/edit.html.erb
<h1>Editing Score Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @score_type %> |
<%= link_to 'Back', score_types_path %>

app/views/score_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Score Types</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @score_types.each do |score_type| %>
      <tr>
        <td><%= score_type.name %></td>
        <td><%= link_to 'Show', score_type %></td>
        <td><%= link_to 'Edit', edit_score_type_path(score_type) %></td>
        <td><%= link_to 'Destroy', score_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score type', new_score_type_path %>

app/views/score_types/new.html.erb
<h1>New Score Type</h1>

<%= render 'form' %>

<%= link_to 'Back', score_types_path %>

app/views/score_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @score_type.name %>
</p>

<p>
  <strong>Arrows:</strong>
  <%= @score_type.arrows %>
</p>

<p>
  <strong>Distance 1:</strong>
  <%= @score_type.distance_1 %>
</p>

<p>
  <strong>Distance 2:</strong>
  <%= @score_type.distance_2 %>
</p>

<p>
  <strong>Distance 3:</strong>
  <%= @score_type.distance_3 %>
</p>

<p>
  <strong>Distance 4:</strong>
  <%= @score_type.distance_4 %>
</p>

<p>
  <strong>Published:</strong>
  <%= @score_type.published %>
</p>

<%= link_to 'Edit', edit_score_type_path(@score_type) %> |
<%= link_to 'Back', score_types_path %>