config/routes.rb
Rails.application.routes.draw do
  
  resources :arrows
  resources :score_types

  resources :scores do 
    member do
      get 'puntuar'
      post 'puntuar'
      post 'add_arrows'
      get 'finish'
    end
  end

  mount Tolk::Engine => '/tolk', :as => 'tolk'
  devise_for :users

  root 'scores#index'

   resources :android do
     collection do
       get 'acceso'
       post 'acceso'
       get 'getsesiones'
       post 'getsesiones'
    end
  end

end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :user
	belongs_to :score_type
	has_many   :arrows, dependent: :destroy
	validates :score_type, :name, :user_id, presence: true

	enum state: [:started, :ended, :deleted]

	before_create :do_create_tasks

	scope :published, -> { where(published: true) }
	scope :not_deleted, -> { where.not(state: Score.states[:deleted]) }
	scope :started, -> { where(state: Score.states[:started]) }
	scope :ended, -> { where(state: Score.states[:ended]) }
	scope :deleted, -> { where(state: Score.states[:deleted]) }

	private
		def do_create_tasks
			# marcar como comenzada
			self.state = Score.states[:started]
			# marcar como privada por defecto
			self.published = false
			# establecemos valores iniciales
			self.points = self.x_count = self.ten_count = self.nine_count = 0
    		self.average = 0.0
		end


	public
		def arrows(round=nil)
			return super if round.nil? 
			return super.where(round: round)
		end

		def puntos_ronda_anterior
			self.arrows.unscope(:order).order('position DESC').limit(6).collect(&:value).sum
		end

		def parcial
			return 0
		end

		def ronda
			(self.arrows.count / self.score_type.round).to_i + 1
		end

		def published?
			return I18n.t('score.publish') if self.published 
			return I18n.t('score.unpublish')
		end

end

app/models/score_type.rb
class ScoreType < ActiveRecord::Base
	has_many :scores

	validates :name, :arrows, :color, presence: true;

	scope :published, -> { where(published: true) }

	def self.import_old_cats
		TipoTirada.all.each do |tt|
			self.where( name: tt.nombre, 
						arrows: tt.numflechas, 
						distance_1: tt.dist1, 
						distance_2: tt.dist2, 
						distance_3: tt.dist3,
						distance_4: tt.dist4,
						target_1: tt.dia1,
						target_2: tt.dia2,
						target_3: tt.dia3,
						target_4: tt.dia4,
						old_type_id: tt.id).first_or_create
		end
	end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  #layout 'app'
  before_action :authenticate_user!
  before_action :set_score, only: [:show, :edit, :update, :destroy, :puntuar, :add_arrows, :finish]
  before_action :set_contadores, only: [:index, :show, :puntuar]

  def finish
    if @score.score_type.num_rounds > @score.actual_round 
      @score.actual_round += 1
      @score.save
    else 
      @score.ended!
    end
    redirect_to @score
  end

  def puntuar
    @arrows = @score.arrows(@score.actual_round)
  end

  def add_arrows
    params[:arrow].each_pair do |param,arrow|
      value = Arrow.get_arrow_value(arrow)
      Arrow.create(score_id: @score.id, value: value, arrow: arrow, round: params[:round])
      # acutalizamos datos del score
      @score.points += value
      @score.x_count += 1 if arrow == 'X'
      @score.ten_count += 1 if arrow == '10'
      @score.nine_count += 1 if value == 9
      @score.average = (@score.points.to_f / @score.arrows.count.to_f).to_f.round(2)
      @score.save
    end
    @arrows = @score.arrows(params[:round])
    if @arrows.count == @score.score_type.arrows
      @time_to_finish = true
    else
      @time_to_finish = false 
    end
  end

  # GET /scores
  # GET /scores.json
  def index
    if current_user.has_role? :admin
      @all = Score.not_deleted
    else
      @all = current_user.scores.not_deleted
    end
    @started = @all.started
    @ended = @all.ended
    @state = params[:state].to_i unless params[:state].blank?
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @arrows = @score.arrows
  end

  # GET /scores/new
  def new
    @score = Score.new()
    @scores = current_user.scores.started
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    @score.name = @score.score_type.name + ' - ' + DateTime.now.strftime('%Y-%m-%d %H:%M') if @score.name.blank?
    @score.user_id = current_user.id
    respond_to do |format|
      if @score.save
        format.html { redirect_to puntuar_score_path(@score) }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    redirect_to action: :index, status: 303, notice: 'Score was successfully destroyed.'
  end

  private
    def set_contadores
      @num_started_scores = current_user.scores.started.count 
      @num_scores = current_user.scores.count
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
      @score_type = @score.score_type
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:name, :score_type_id, :user_id, :state, :published, :points, :average, :x_count, :ten_count, :nine_count)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_datos_parciales_score.html.erb
<div id="datos-score">
	<div class="score_icon_puntuar">
		<div id="acumulacion" class="inline-block"><%= @score.points %></div>
		<div class="pts"><%= t('score.pts_sin_punto') %></div>
	</div>
	<div class="block">
		<div class="parciales_pts">
			<div class="block"><%= t 'score.anterior' %></div>
			<div class="parcial_icon_puntos">
				<div id="ronda_anterior" class="inline-block"><%= @score.puntos_ronda_anterior %></div>
				<div class="pts"><%= t 'score.pts_sin_punto' %></div>
			</div>
		</div>
		<div class="parciales_pts">
			<div class="block"><%= t 'score.actual' %></div>
			<div class="parcial_icon_puntos">
				<div id="parcial"><%= @score.parcial %></div>
				<div class="pts"><%= t 'score.pts_sin_punto' %></div>
			</div>
		</div>
	</div>
	<div class="media">
		<h4>
			<div class="block"><%= t 'score.avg' %></div>
			<div class="inline-block" id="media"><%= @score.average %></div>
			<div class="inline-block"><%= t 'score.pts' %></div>
		</h4>
	</div>

	<div class="ronda">
		<h4>
			<div class="inline-block"><%= t 'score.ronda' %></div>
			<div class="inline-block" id="ronda"><%= @score.ronda %></div>
		</h4>
	</div>


	<%= link_to t('score.reset'), '#', on_click: 'resetear();', class: 'btn btn-primary btn-big resetear hidden' %>
	<%= link_to t('score.finished').html_safe, finish_score_path(@score), class: 'btn btn-primary btn-big finish hidden', remote: true %>
</div>

app/views/scores/_menu.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li>
            <%= link_to t('score.list_scores').html_safe, scores_path, remote: true %>
        </li>
        <%= render 'score_board' unless @arrows.blank? %>
        <li>
        <%= link_to(t('main.close_session').html_safe, destroy_user_session_path, :method => :delete) %>
        </li>
    </ul>
</div>

app/views/scores/_menu_puntuar.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li>
            <%= link_to t('score.list_scores').html_safe, scores_path, remote: true %>
        </li>
        <%= render 'score_board' unless @arrows.blank? %>
        <li>
        <%= link_to(t('main.close_session').html_safe, destroy_user_session_path, :method => :delete) %>
        </li>
    </ul>
</div>

app/views/scores/_menu_score.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="menu_score">
    <ul class="menu">


        <li>
        	<%= link_to t('score.edit').html_safe, edit_score_path(@score), remote: true %>
        </li>

        <li>
        	<%= link_to t('main.destroy').html_safe, @score, method: :delete, remote: true, data: { confirm: t('main.confirm_delete') } %>
        </li>

    </ul>
</div>

app/views/scores/_new.html.erb
<%= content_for :bar_options do %>
  <%= render 'scores/bar_options_new' %>  
<% end %>

<div class="acenter">
	<h4><%= t('score.new').html_safe %></h4>
	<%= render 'form' %>
</div>

<h4 class="mtop30"><%= t'score.continuar' %></h4>
<ul class="listado">
  <% @scores.each do |score| %>
    <%= render 'scores/score_field', score: score %>
  <% end %>
</ul>

app/views/scores/_partial_score.html.erb
<div class="partial_score">
	<div class="">
		<div class="arrow">
			<%= text_field_tag "arrow_1",'', id: 'arrow_1', class: 'parciales borde', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_2",'', id: 'arrow_2', class: 'parciales borde', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_3",'', id: 'arrow_3', class: 'parciales borde', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "partial_1",'0', id: 'partial_1', class: 'suma_parcial borde', disabled: true %>
		</div>
	</div>
	<div class="">
		<div class="arrow">
			<%= text_field_tag "arrow_4",'', id: 'arrow_4', class: 'parciales', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_5",'', id: 'arrow_5', class: 'parciales', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_6",'', id: 'arrow_6', class: 'parciales', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "partial_2",'0', id: 'partial_2', class: 'suma_parcial', disabled: true %>
		</div>
	</div>
</div>

app/views/scores/_puntuar.html.erb
<%= content_for :bar_options do %>
	<%= render 'scores/bar_options_puntuar' %>
<% end %>

<%= content_for :menu_desplegable_puntuar do %>
	<%= render 'scores/score_board' %>
<% end %>

<%= render 'scores/datos_parciales_score' %>
<%= render 'scores/partial_score' %>
<%= render 'scores/keyboard' %>

app/views/scores/_score_board.html.erb
<% if @arrows.count > 0%>
	<% dist = 1 %>
	<% if @arrows.count > @score_type.arrows %>
		<% grupo = @score_type.arrows %>
	<% else %>
		<% grupo = @arrows.count %>
	<% end %>

	<% @arrows.in_groups_of(grupo) do |arrows| %>
		<ul>
			<li><strong><%= t('score.tabla_puntos_dist',dist: @score_type.send("distance_#{dist}")) %></strong></li>
			<% acumulado = 0 %>
			<% partial_bis = 0 %>
			<% sacar_partial = false %>
			<% arrows.in_groups_of(3) do |arrow| %>
				<% partial = arrow[0].value + arrow[1].value + arrow[2].value %>
				<% partial_bis += partial %>
				<% acumulado += partial %>
				<li class="board">
					<div class="score_arrow"><%= arrow[0].arrow %></div>
					<div class="score_arrow"><%= arrow[1].arrow %></div>
					<div class="score_arrow"><%= arrow[2].arrow %></div>
					<div class="score_arrow partial_cell"><%= partial %></div>
					<% if sacar_partial %>
						<div class="score_arrow partial_cell"><%= partial_bis %></div>
						<% sacar_partial = false %>
						<% partial_bis = 0 %>
					<% else %>
						<div class="score_arrow partial_cell"> </div>
						<% sacar_partial = true %>
					<% end %>
					<div class="score_arrow total_cell"><%= acumulado %></div>
				</li>
			<% end %>
		</ul>
		<% dist += 1 %>
	<% end %>
<% else %>
	<ul>
		<li><%= t 'score.tabla_puntos_vacia' %></li>
	</ul>
<% end %>

app/views/scores/_score_field.html.erb
<li>
  <%= link_to score, remote: true do %>
    <div class="score_icon" style="background-color: <%= score.score_type.color %>">
    	<%= score.points %>
    	<div class="pts"><%= t('score.pts_sin_punto') %></div>
    </div>
    <div class="score_data">
      <div class="score_name"><%= score.name %></div>
      <div class="score_type"><%= score.score_type.name rescue 'Sesión libre' %></div>
      <div class="score_average"><%= t('score.average') + ' ' + score.average.to_s %></div>
    </div>
    <div class="score_navigate"><%= material_icon.navigate_next.md_36 %></div>
  <% end %>
</li>

app/views/scores/add_arrows.js.erb
$(".menu_desplegable_puntuar").show();

//$('#loading').addClass('hidden');

$(".menu_desplegable_puntuar").html("<%= raw escape_javascript(render 'scores/score_board') %>");

<% if @time_to_finish %>
	$('.finish').removeClass('hidden');
<% else %>
	$('#ronda').html(parseInt($('#ronda').html())+1);
	$('.resetear').removeClass('hidden');
<% end %>

app/views/scores/index.js.erb
$('.tabs_content').show();
$("#app_container").html("<%= raw escape_javascript(render 'scores/index') %>");
$(".tabs_content").html("<%= raw escape_javascript(render 'shared/tabs') %>");
$(".bar_opts").hide();

app/views/scores/new.html.erb
<%= render 'scores/new' %>

app/views/scores/new.js.erb
$("#app_container").html("<%= raw escape_javascript(render 'scores/new') %>");
$(".bar_opts").html("<%= raw escape_javascript(render 'scores/bar_options_new') %>");

app/views/scores/puntuar.html.erb
<%= render 'scores/puntuar' %>