config/routes.rb
Rails.application.routes.draw do
  
  resources :arrows
  resources :score_types

  resources :scores do 
    member do
      get 'puntuar'
      post 'puntuar'
      post 'add_arrows'
      get 'finish'
    end
  end

  mount Tolk::Engine => '/tolk', :as => 'tolk'
  devise_for :users

  root 'scores#index'

   resources :android do
     collection do
       get 'acceso'
       post 'acceso'
       get 'getsesiones'
       post 'getsesiones'
    end
  end

end

app/views/shared/_btn_loading.html.erb
<i class="material-icons spin md-30">refresh</i>

app/views/shared/_btn_menu.html.erb
<%= material_icon.menu.md_36 %>

app/views/shared/_error_messages.html.erb
<% if flash[:error] || flash[:notice] %>
    <div class="flash-message">
        <div class="mensajes">
            <p id="error"><%= flash[:error] %></p>
            <p id="notice"><%= flash[:notice] %></p>
        </div>
    </div>
<% end %>

app/views/shared/_menu.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="content_menu left_minus_100">
    <div class="menu_header">
        <div class="sombreado"></div>
        <%= image_tag 'default_header.jpg' %>
    </div>
    <ul class="list_menu">
        <li>
            <%= link_to new_score_path, remote: true do %>
                <%= t('score.new_score').html_safe %>
            <% end %>
        </li>

        <li>
            <%= link_to scores_path(state: Score.states[:started]), remote: true do %>
                <%= t('score.list_started').html_safe %>
                <span id="num_started_scores"><%= @num_started_scores.blank? ? current_user.scores.started.count : @num_started_scores %></span>
            <% end %>
        </li>

        <li>
            <%= link_to scores_path, remote: true do %>
	            <%= t('score.list_scores').html_safe %>
	            <span id="num_scores"><%= @num_scores.blank? ? current_user.scores.count : @num_scores %></span>
	        <% end %>
        </li>
        
        <%= yield :menu %>

        <li>
        <%= link_to(t('main.close_session').html_safe, destroy_user_session_path, :method => :delete) %>
        </li>
    </ul>
</div>

app/views/shared/_notices.html.erb
<% unless notice.blank? %>
	<div class="toast">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>

<script>
	$(document).on('page:load ready', function(){
		$('.toast').addClass('toast_show');
		setTimeout(function(){ $('.toast').removeClass('toast_show'); }, 5000);
	});
</script>

app/views/shared/_tabs.html.erb
<div class="tabs">
  <div class="tab all rwidth33 <%= 'selected' if @state.nil? %>">
    <%= link_to t('scores.list_all'), '#', onclick: "scroll_to('all');", class: 'tab_link' %>
  </div>
  <div class="tab started rwidth33 <%= 'selected' if @state==Score.states[:started] %>">
    <%= link_to t('scores.list_started'), '#', onclick: "scroll_to('started');", class: 'tab_link' %>
  </div>
  <div class="tab ended rwidth33 <%= 'selected' if @state==Score.states[:ended] %>">
    <%= link_to t('scores.list_finished'), '#', onclick: "scroll_to('ended');", class: 'tab_link' %>
  </div>
</div>


<script>
  $('.tab_link').click(function(){
    $('.tab').removeClass('selected');
    $(this).parent().addClass('selected');
  });
</script>