config/routes.rb
Rails.application.routes.draw do
  
  resources :arrows
  resources :score_types

  resources :scores do 
    member do
      get 'puntuar'
      post 'puntuar'
      post 'add_arrows'
      get 'finish'
    end
  end

  mount Tolk::Engine => '/tolk', :as => 'tolk'
  devise_for :users

  root 'scores#index'

   resources :android do
     collection do
       get 'acceso'
       post 'acceso'
       get 'getsesiones'
       post 'getsesiones'
    end
  end

end

app/models/arrow.rb
class Arrow < ActiveRecord::Base
	belongs_to :score
	validates :score_id, :value, :arrow, presence: true

	before_create :do_create_tasks

	default_scope { order('position ASC') } 

	private
		def do_create_tasks
			# establecemos la posición
			self.position = (Arrow.where(score_id: self.score_id).where.not(id: self.score_id).last.position)+1 rescue 1
		end

	public
		def self.get_arrow_value arrow 
			return 10 if arrow == 'X'
			return 0 if arrow == 'M'
			return arrow.to_i
		end
end

app/controllers/arrows_controller.rb
class ArrowsController < ApplicationController
  before_action :set_arrow, only: [:show, :edit, :update, :destroy]

  # GET /arrows
  # GET /arrows.json
  def index
    @arrows = Arrow.all
  end

  # GET /arrows/1
  # GET /arrows/1.json
  def show
  end

  # GET /arrows/new
  def new
    @arrow = Arrow.new
  end

  # GET /arrows/1/edit
  def edit
  end

  # POST /arrows
  # POST /arrows.json
  def create
    @arrow = Arrow.new(arrow_params)

    respond_to do |format|
      if @arrow.save
        format.html { redirect_to @arrow, notice: 'Arrow was successfully created.' }
        format.json { render :show, status: :created, location: @arrow }
      else
        format.html { render :new }
        format.json { render json: @arrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arrows/1
  # PATCH/PUT /arrows/1.json
  def update
    respond_to do |format|
      if @arrow.update(arrow_params)
        format.html { redirect_to @arrow, notice: 'Arrow was successfully updated.' }
        format.json { render :show, status: :ok, location: @arrow }
      else
        format.html { render :edit }
        format.json { render json: @arrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arrows/1
  # DELETE /arrows/1.json
  def destroy
    @arrow.destroy
    respond_to do |format|
      format.html { redirect_to arrows_url, notice: 'Arrow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arrow
      @arrow = Arrow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arrow_params
      params.require(:arrow).permit(:score_id, :value)
    end
end

app/helpers/arrows_helper.rb
module ArrowsHelper
end

app/views/arrows/_form.html.erb
<%= form_for(@arrow) do |f| %>
  <% if @arrow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@arrow.errors.count, "error") %> prohibited this arrow from being saved:</h2>

      <ul>
      <% @arrow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score_id %><br>
    <%= f.number_field :score_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arrows/edit.html.erb
<h1>Editing Arrow</h1>

<%= render 'form' %>

<%= link_to 'Show', @arrow %> |
<%= link_to 'Back', arrows_path %>

app/views/arrows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Arrows</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arrows.each do |arrow| %>
      <tr>
        <td><%= arrow.score_id %></td>
        <td><%= arrow.value %></td>
        <td><%= link_to 'Show', arrow %></td>
        <td><%= link_to 'Edit', edit_arrow_path(arrow) %></td>
        <td><%= link_to 'Destroy', arrow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arrow', new_arrow_path %>

app/views/arrows/new.html.erb
<h1>New Arrow</h1>

<%= render 'form' %>

<%= link_to 'Back', arrows_path %>

app/views/arrows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @arrow.score_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @arrow.value %>
</p>

<%= link_to 'Edit', edit_arrow_path(@arrow) %> |
<%= link_to 'Back', arrows_path %>